

name: 'sp_crime_dbt'
version: '1.0.0'

profile: 'sp_crime_dbt'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:    
  - "target"
  - "dbt_packages"


models:
  sp_crime_dbt:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
      
seeds:
  sp_crime_dbt:
    +schema: sp_crime_landing
